export const mockLeads = [
    {
        id: 1,
        name: "Sarah Parker",
        avatar: "https://i.pravatar.cc/150?u=1",
        status: "Won",
        score: "Interested",
        scoreIcon: "star",
        tags: ["Automations"],
        message: "Sponsored Ad",
        dealValue: 2500,
        assignedTo: { name: "Sarah", avatar: "https://i.pravatar.cc/150?u=20" },
        interacted: "2 days ago",
        unreadMessages: 3,
        email: "sarah.parker@example.com"
    },
    {
        id: 2,
        name: "Mike Brown",
        avatar: "https://i.pravatar.cc/150?u=2",
        status: "Call Booked",
        score: "Interested",
        scoreIcon: "star",
        tags: [],
        message: "Sponsored Ad",
        dealValue: null,
        assignedTo: { name: "Alex", avatar: "https://i.pravatar.cc/150?u=21" },
        interacted: "3 hours ago",
        unreadMessages: 0,
        email: "mike.brown@example.com"
    },
    {
        id: 3,
        name: "Linda Chen",
        avatar: "https://i.pravatar.cc/150?u=3",
        status: "Unqualified",
        score: "Interested",
        scoreIcon: "star",
        tags: [],
        message: "Sponsored Ad",
        dealValue: null,
        assignedTo: { name: "Jane", avatar: "https://i.pravatar.cc/150?u=22" },
        interacted: "1 week ago",
        unreadMessages: 0,
        email: "linda.chen@example.com"
    },
    {
        id: 4,
        name: "David Lee",
        avatar: "https://i.pravatar.cc/150?u=4",
        status: "Won",
        score: "Interested",
        scoreIcon: "star",
        tags: [],
        message: "Direct Message",
        dealValue: 5000,
        assignedTo: { name: "Gav", avatar: "https://i.pravatar.cc/150?u=23" },
        interacted: "4 days ago",
        unreadMessages: 0,
        email: "david.lee@example.com"
    },
    {
        id: 5,
        name: "Emily White",
        avatar: "https://i.pravatar.cc/150?u=5",
        status: "No Show",
        score: "N/A",
        scoreIcon: null,
        tags: [],
        message: "Story - Replies Ret...",
        dealValue: null,
        assignedTo: { name: "Jia", avatar: "https://i.pravatar.cc/150?u=24" },
        interacted: "15 mins ago",
        unreadMessages: 5,
        email: "emily.white@example.com"
    },
    {
        id: 6,
        name: "Jessica Wong",
        avatar: "https://i.pravatar.cc/150?u=6",
        status: "Won",
        score: "N/A",
        scoreIcon: null,
        tags: [],
        message: "Direct Message",
        dealValue: 3000,
        assignedTo: { name: "Sarah", avatar: "https://i.pravatar.cc/150?u=20" },
        interacted: "1 week ago",
        unreadMessages: 0,
        email: "jessica.wong@example.com"
    },
    {
        id: 7,
        name: "Kevin Harris",
        avatar: "https://i.pravatar.cc/150?u=7",
        status: "Qualified",
        score: "Automations",
        scoreIcon: "zap",
        tags: [],
        message: "Direct Message",
        dealValue: null,
        assignedTo: { name: "Jane", avatar: "https://i.pravatar.cc/150?u=22" },
        interacted: "1 day ago",
        unreadMessages: 0,
        email: "kevin.harris@example.com"
    },
    {
        id: 8,
        name: "Tom Clark",
        avatar: "https://i.pravatar.cc/150?u=8",
        status: "Lost",
        score: "Broke",
        scoreIcon: "dollar-sign",
        tags: [],
        message: "Direct Message",
        dealValue: null,
        assignedTo: { name: "Gav", avatar: "https://i.pravatar.cc/150?u=23" },
        interacted: "6 days ago",
        unreadMessages: 0,
        email: "tom.clark@example.com"
    },
    {
        id: 9,
        name: "Laura Lewis",
        avatar: "https://i.pravatar.cc/150?u=9",
        status: "New Lead",
        score: "Broke",
        scoreIcon: "dollar-sign",
        tags: [],
        message: "Direct Message",
        dealValue: null,
        assignedTo: { name: "Jia", avatar: "https://i.pravatar.cc/150?u=24" },
        interacted: "30 mins ago",
        unreadMessages: 0,
        email: "laura.lewis@example.com"
    },
    {
        id: 10,
        name: "Brian Walker",
        avatar: "https://i.pravatar.cc/150?u=10",
        status: "Call Booked",
        score: "Achiever",
        scoreIcon: "award",
        tags: [],
        message: "Direct Message",
        dealValue: null,
        assignedTo: { name: "Alex", avatar: "https://i.pravatar.cc/150?u=21" },
        interacted: "2 days ago",
        unreadMessages: 1,
        email: "brian.walker@example.com"
    }
];

export const leadStatuses = [
    "New Lead", "Qualified", "Call Booked", "Won", "Qualified",
    "Unqualified",
    "No Show",
    "Needs Followup",
    "Cold"
];

export const scoreTags = [
    { label: "Interested", icon: "star" },
    { label: "Automations", icon: "zap" },
    { label: "Achiever", icon: "award" },
    { label: "Broke", icon: "dollar-sign" },
    { label: "Explorer", icon: "search" }
];
